import type { Dialect } from "@/Mapping/dialect.js";
import { pgType } from "@/Mapping/plan.js";
import type { Plan } from "@/Mapping/types.js";

/**
 * Postgres DDL for every table the generated jobs write to.
 *
 * The jobs never create tables (the JDBC writer only inserts/upserts), and
 * neither the staging tables nor the FDL tables exist yet for this model - so
 * the DDL is generated from the same plan, guaranteeing column names and types
 * match what the writers send.
 */
export function buildDdl(plan: Plan, target: Dialect): string {
	const q = target.quote;
	const out: string[] = [
		"-- Generated by finaqua-ide-template-migration-fdl. Postgres.",
		"-- Run once in the target database before the first load.",
		"",
		"-- Control tables used by every job (batch run lookup + audit/recon).",
		"create table if not exists batch_run_detail (",
		"\tbatch_run_id integer primary key,",
		"\tbatch_name text not null,",
		"\tstatus text not null,",
		"\tstart_time timestamp,",
		"\tend_time timestamp",
		");",
		"",
		"create table if not exists audit_log_detail (",
		"\tbatch_run_id integer,",
		"\tbatch_name text,",
		"\ttarget_table_name text,",
		"\tsource_row_count bigint,",
		"\ttarget_row_count bigint,",
		"\trecon_success_status char(1),",
		"\tload_status text,",
		"\tlayer text,",
		"\tload_date timestamp,",
		"\tmin_data_persistance_time timestamp,",
		"\tmax_data_persistance_time timestamp",
		");",
		"create index if not exists audit_log_detail_table_idx on audit_log_detail (target_table_name);",
		"",
		"-- Bronze: staging copies of the source tables.",
	];

	const table = (name: string, columns: string[], keyed: boolean) => {
		out.push(`create table if not exists ${q(name)} (`);
		out.push(columns.map((c) => `\t${c}`).join(",\n"));
		out.push(");");
		// Upsert matches on business_column_value, which needs a unique index.
		// Postgres treats NULLs as distinct, so a NULL key never conflicts.
		if (keyed) {
			out.push(
				`create unique index if not exists ${name}_bcv_uk on ${q(name)} (business_column_value);`,
			);
		}
		out.push("");
	};

	for (const b of plan.bronze) {
		const keyed = b.key.length > 0;
		table(
			b.staging,
			[
				"batch_run_id integer",
				...b.columns.map((c) => `${q(c.name)} ${pgType(c.type)}`),
				...(keyed
					? ["business_column_name text", "business_column_value text"]
					: []),
			],
			keyed,
		);
	}

	out.push("-- Silver: FDL entities.");
	for (const s of plan.silver) {
		table(
			s.name,
			[
				"batch_run_id integer",
				...s.columns.map((c) => `${q(c.name)} ${pgType(c.type)}`),
			],
			s.keyed,
		);
	}

	return out.join("\n");
}
